# Generated by Django 5.2.4 on 2025-07-26 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archaeology', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='news',
            options={'ordering': ['-order'], 'verbose_name': 'New', 'verbose_name_plural': 'News'},
        ),
        migrations.AddField(
            model_name='news',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
