# Generated by Django 5.2.4 on 2025-08-11 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archaeology', '0002_alter_news_options_news_order'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='archaeologypicture',
            options={'ordering': ['order']},
        ),
        migrations.AddField(
            model_name='archaeologypicture',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
