# Generated by Django 5.0.6 on 2024-10-23 08:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archaeology', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArchaeologyType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=60)),
                ('image', models.FileField(blank=True, null=True, upload_to='image')),
            ],
        ),
        migrations.RemoveField(
            model_name='archaeology',
            name='users',
        ),
        migrations.RemoveField(
            model_name='items',
            name='users',
        ),
        migrations.AddField(
            model_name='category',
            name='icon',
            field=models.ImageField(default=2, upload_to='icon/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='category',
            name='image',
            field=models.ImageField(default=2, upload_to='image/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='items',
            name='archaeology_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='items_type', to='archaeology.archaeologytype'),
        ),
    ]
