# Generated by Django 5.2.4 on 2025-08-12 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archaeology', '0003_alter_archaeologypicture_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='create',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='news',
            name='update',
            field=models.DateTimeField(),
        ),
    ]
