# Generated by Django 5.0.1 on 2024-10-26 10:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archaeology', '0003_archaeologytype_remove_archaeology_users_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='archaeology_type',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='archaeology.archaeologytype'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='archaeologytype',
            name='image',
            field=models.ImageField(default=2, upload_to='image/'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='archaeologytype',
            name='title',
            field=models.CharField(max_length=255),
        ),
    ]
