# Generated by Django 5.2.4 on 2025-08-13 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archaeology', '0004_alter_news_create_alter_news_update'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='title',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='news',
            name='title_en',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='news',
            name='title_ru',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='news',
            name='title_uz',
            field=models.TextField(null=True),
        ),
    ]
