# Generated by Django 5.0.1 on 2024-10-27 10:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archaeology', '0005_alter_archaeologytype_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='archaeology_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='archaeology.archaeologytype'),
        ),
    ]
