# Generated by Django 5.1.6 on 2025-02-20 11:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('archaeology', '0006_alter_category_archaeology_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='items',
            name='archaeology_type',
        ),
        migrations.RemoveField(
            model_name='category',
            name='archaeology_type',
        ),
        migrations.RemoveField(
            model_name='items',
            name='link',
        ),
        migrations.RemoveField(
            model_name='items',
            name='video',
        ),
        migrations.RemoveField(
            model_name='items',
            name='video_link',
        ),
        migrations.DeleteModel(
            name='ArchaeologyType',
        ),
    ]
