# Generated by Django 5.1.6 on 2025-02-20 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archaeology', '0007_remove_items_archaeology_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='items',
            name='link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='items',
            name='video_link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
